project:
  type: website

website:
  title: "ICHRA Connect"
  favicon: OscarLogoTransparent.png
  google-analytics: "G-TT9QQLNB0E"
  navbar:
    logo: OscarLogoTransparent.png
    logo-alt: Oscar Health
    right:
      - text: "Oscar"
        href: https://www.hioscar.com/
        target: _blank
  sidebar:
    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: "**Getting Started**"
        contents:
          - index.qmd
          - integrating_with_oscar.qmd
          - text: "Oscar ICHRA for Employers"
            href: https://www.hioscar.com/ichra
            target: _blank
      - section: "**EDI**"
        contents:
          - text: "Implementation Guide"
            href: edi_implementation_guide.qmd
          - section: "Sample File Downloads"
            contents:
              - text: Inbound 834 EDI
                href: sample_files/FROM_VENDOR.I834.D20241114.T125545.P.edi
                target: _blank
              - text: Outbound 834 EDI
                href: sample_files/TO_VENDOR.I834.D20241114.T113452.P.edi
                target: _blank
              - text: Inbound 820 EDI
                href: sample_files/EDI.820.D20241114.T082645.P.edi
                target: _blank
      - section: "**CSV**"
        contents:
          - text: "Implementation Guide"
            href: csv/csv_implementation_guide.qmd
          - section: "File Specifications"
            contents:
              - csv/file_spec/file_spec.qmd
              - csv/file_spec/inbound_enrollment_spec.qmd
              - csv/file_spec/outbound_enrollment_ack_spec.qmd
              - csv/file_spec/outbound_enrollment_spec.qmd
              - csv/file_spec/outbound_reconcilliation_spec.qmd
          - text: "Test Cases and Downloads"
            href: csv/test_cases_guide.qmd
          - section: "Additional Sample Downloads"
            contents:
              - text: Inbound Enrollment CSV
                href: csv/sample_files/FROM_VENDOR.EMT.20240923T104016.T.csv
                target: _blank
              - text: Outbound Enrollment Ack CSV
                href: csv/sample_files/FROM_OSCAR.ACK.20240912T020212.T.csv
                target: _blank
              - text: Outbound Enrollment CSV
                href: csv/sample_files/FROM_OSCAR.OUT.20240912T224634.T.csv
                target: _blank
              - text: Reconcilation CSV
                href: csv/sample_files/FROM_OSCAR_SNAPSHOT.OUT.20241015T190751.P.csv
                target: _blank
      - section: "**Field Specs**"
        contents:
          - relationship_code_mapping.qmd
          - ethnicity_code_mapping.qmd
          - language_mapping.qmd
          - marital_status_mapping.qmd
          - supported_qle_codes.qmd
          - additional_maintenance_reasons.qmd
      - section: "**File Validators**"
        contents:
          - csv_validator.qmd
      - text: "**Coming Soon: REST API**"
        href: rest_api.qmd

  page-footer:
    center:
      - text: © 2024 Oscar Management Corporation, Licensed under the Apache License, version 2.0
        href: license.qmd
      - text: "Terms of Service"
        href: https://www.hioscar.com/legal/terms
      - text: "Privacy Policy"
        href: https://www.hioscar.com/legal/privacy
      - text: "Do Not Sell My Information"
        href: https://www.hioscar.com/privacy-request

format:
  html:
    grid:
      sidebar-width: 300px
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    page-layout: full
    linkcolor: "#4f50f6"
    include-in-header:
      - text: |
          <script type="text/javascript">
          // Redirect all routes except csv_validator.html and asset files
          (function() {
            var path = window.location.pathname;

            // Don't redirect if we're on the csv_validator.html page
            if (path.endsWith('/csv_validator.html') || path === '/csv_validator.html') {
              return; // Let the page load normally
            }

            // Don't redirect asset files (images, css, js, documents, etc.)
            var assetExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.ico',
                                  '.css', '.js', '.json', '.xml', '.txt',
                                  '.pdf', '.csv', '.edi'];

            for (var i = 0; i < assetExtensions.length; i++) {
              if (path.endsWith(assetExtensions[i])) {
                return; // Let asset files load normally
              }
            }

            // Generic redirect: convert any .html page to ReadMe docs URL
            if (path.endsWith('.html')) {
              // Extract filename from path (remove directories)
              var filename = path.split('/').pop();
              // Remove .html extension and convert underscores to hyphens
              var docName = filename.replace('.html', '').replace(/_/g, '-');
              window.location.replace('https://ichra-connect.readme.io/docs/' + docName);
              return;
            }

            // Default redirect to homepage for all other routes
            window.location.replace('https://ichra-connect.readme.io/');
          })();
          </script>